"""Subtitle generation service (ASS format)."""
from __future__ import annotations

from pathlib import Path

from app.models.shot import ShotModel


class SubtitleService:
    """Generate Advanced SubStation Alpha (ASS) subtitles from shot scripts."""

    ASS_HEADER = """[Script Info]
; ASS subtitle file generated by AI 2D Pipeline
ScriptType: v4.00+
PlayResX: {width}
PlayResY: {height}
ScaledBorderAndShadow: yes
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{fontname},{fontsize},&H00FFFF,&H000000,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,2,1,2,20,20,30,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    @classmethod
    def generate_subs(cls, shots: list[ShotModel], width: int = 1080, height: int = 1920,
                      fontname: str = "Noto Sans SC", fontsize: int = 28) -> str:
        """Generate complete ASS subtitle content from a list of shots."""
        lines = [cls.ASS_HEADER.format(width=width, height=height,
                                        fontname=fontname, fontsize=fontsize)]
        current_time = 0.0

        for shot in shots:
            dur = shot.duration_seconds or 4.0
            text = shot.description or shot.generation_prompt or ""
            if not text:
                current_time += dur
                continue

            start_ts = cls._format_time(current_time)
            end_ts = cls._format_time(current_time + dur)
            # Escape special chars for ASS
            safe_text = text.replace("{", "\\{").replace("}", "\\}")
            lines.append(f"Dialogue: 0,{start_ts},{end_ts},Default,,0,0,0,,{safe_text}")
            current_time += dur

        return "".join(lines)

    @staticmethod
    def _format_time(seconds: float) -> str:
        """Convert seconds to ASS timestamp format (H:MM:SS.cc)."""
        h = int(seconds // 3600)
        m = int((seconds % 3600) // 60)
        s = int(seconds % 60)
        cs = int((seconds - int(seconds)) * 100)
        return f"{h}:{m:02d}:{s:02d}.{cs:02d}"

    @staticmethod
    def get_overlay_filter(sub_path: Path) -> str:
        """FFmpeg filter string for subtitle overlay."""
        return f"subtitles={sub_path}:force_style='FontName=Noto Sans SC,FontSize=26,PrimaryColour=&H00FFFF&,OutlineColour=&H000000&,BorderStyle=1,Outline=2,MarginV=40'"
